### ISSUE TITLE
out_of_china判断

### ISSUE THREAD

**Issue by 1040223592** [wandergis/coordTransform_py#1]
def out_of_china(lng, lat):
    """
    判断是否在国内，不在国内不做偏移
    :param lng:
    :param lat:
    :return:
    """
    if lng < 72.004 or lng > 137.8347:
        return True
    if lat < 0.8293 or lat > 55.8271:
        return True
    return False

这两个if判断个人认为不能准确判断是否在国内，中国形状不是规则矩形

**Comment by wandergis** [comment]
嗯，外包矩形粗判断
