### ISSUE TITLE
返回类型一致性优化

### ISSUE THREAD

**Issue by QLWeilcf** [wandergis/coordTransform_py#11]
我觉得代码里的：
```
if out_of_china(lng, lat): 
        return lng, lat
```
写成：
```
if out_of_china(lng, lat):
        return [lng, lat]
```
会更好些吧？其他情况都是返回列表类型，超出中国范围返回元组，虽然在调用和引用值时基本没有问题，都可以用result[0],result[1]获取返回的经纬度，还是觉得return [lng, lat]更优雅些。

**Comment by wandergis** [comment]
建议很好，您可以提一个pr给我，我来合并
