### ISSUE TITLE
请问g2w，结果只是经纬度互换了...

### ISSUE THREAD

**Issue by comhoo** [wandergis/coordTransform_py#20]
这个是源数据，第一列是lng，第二列是lat
![image](https://user-images.githubusercontent.com/49826277/57417208-253bfe80-7236-11e9-88ef-852728205f5a.png)

导出来之后，第一列是lat，第二列是lng，数值没变...
![image](https://user-images.githubusercontent.com/49826277/57417192-18b7a600-7236-11e9-9d0f-0be4b12a81fb.png)

**Comment by comhoo** [comment]
在coordTransform_utils.py里执行时，是可以执行g2w的...

**Comment by comhoo** [comment]
但是用csv批量做，就出现了bug...求分析，谢谢

**Comment by wandergis** [comment]
@zuzhi 麻烦看下这个issue

**Comment by comhoo** [comment]
已解决

**Comment by zuzhi** [comment]
csv格式是 lat,lng @comhoo 是这个导致的是吧？

**Comment by zuzhi** [comment]
这里应该和原项目一致，使用 lng,lat 的顺序，我修改一下

**Comment by comhoo** [comment]
嗯，是的，顺序错了
