### ISSUE TITLE
spheroid parameters

### ISSUE THREAD

**Issue by weepingdog** [wandergis/coordTransform_py#9]
https://github.com/wandergis/coordTransform_py/blob/7adb3fe542bac22bf6c1d3c8b63719178eeb85ce/coordTransform_utils.py#L9
注释有误，应改为“偏心率平方”。 
备注：偏心率常用e表示，e=sqrt(a^2-b^2)/a, ee=e^2；扁率常用f表示，f=(a-b)/a

**Comment by wandergis** [comment]
感谢提醒，已经修正。

**Comment by weepingdog** [comment]
客气。。。你反应太快了。刚核实了下资料，我有些概念记错了，你再改一下吧
http://baike.baidu.com/client/view/475453.htm

**Comment by wandergis** [comment]
啊哈哈，正好看到了，感谢指正。
